package dev.riko.golftourplanner.utils;

import dev.riko.golftourplanner.world.facility.Facility;
import dev.riko.golftourplanner.world.facility.FacilityType;
import dev.riko.golftourplanner.world.place.Place;

import java.util.*;

import static dev.riko.golftourplanner.world.facility.FacilityType.*;

/**
 * The {@code GenerateData} class generates a list of random places with various attributes such as latitude,
 * longitude, title, rating, facilities, population, and road connections. It also generates connections between places based on their distance.
 */
public class GenerateData {
    /**
     * The list of places generated by the class.
     */
    private final List<Place> placesData;
    /**
     * The random number generator used by the class.
     */
    private final Random random = new Random(System.currentTimeMillis());
    /**
     * A list of vowels used in generating random titles for the places.
     */
    private final static List<String> vowels = new ArrayList<>(Arrays.asList("a", "e", "i", "o", "u"));
    /**
     * A list of consonants used in generating random titles for the places.
     */
    private final static List<String> consonants = new ArrayList<>(Arrays.asList("b", "c", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "v", "w", "x", "y", "z"));

    /**
     * Constructs a GenerateData object and generates a list of places with the specified amount.
     *
     * @param amount the amount of places to generate.
     */
    public GenerateData(int amount) {
        this.placesData = generateData(amount);
    }

    /**
     * Generates a list of random places with the specified amount.
     *
     * @param amount the amount of places to generate.
     * @return a list of random places.
     */
    private List<Place> generateData(int amount) {
        List<Place> data = new ArrayList<>();
        Set<String> titles = new HashSet<>();

        for (int i = 0; i < amount; i++) {
            double lat = random.nextDouble(0, amount);
            double lon = random.nextDouble(0, amount);

            String title = String.valueOf((char) random.nextInt(65, 91));
            int titleLength = random.nextInt(1, 10);

            for (int j = 0; j < titleLength; j++) {
                String prev = String.valueOf(title.charAt(j)).toLowerCase();
                if (vowels.contains(prev)) {
                    if (random.nextInt(101) < 91) {
                        title = title.concat(String.valueOf(consonants.get(random.nextInt(consonants.size()))));
                    } else {
                        title = title.concat(String.valueOf(vowels.get(random.nextInt(vowels.size()))));
                    }
                } else {
                    if (random.nextInt(101) < 91)
                        title = title.concat(String.valueOf(vowels.get(random.nextInt(vowels.size()))));
                    else title = title.concat(String.valueOf(consonants.get(random.nextInt(consonants.size()))));
                }
            }

            float rating = random.nextFloat(0, 10);

            List<Facility> facilityList = new ArrayList<>();
            facilityList.add(new Facility(SHOP, lat, lon));
            if (random.nextBoolean()) facilityList.add(new Facility(GAS_STATION, lat, lon));
            if (random.nextBoolean()) facilityList.add(new Facility(HOSTEL, lat, lon));
            if (rating >= 2) if (random.nextBoolean()) facilityList.add(new Facility(SUPERMARKET, lat, lon));
            if (rating >= 3) if (random.nextBoolean()) facilityList.add(new Facility(RESTAURANTS, lat, lon));
            if (rating >= 6) {
                if (random.nextBoolean()) facilityList.add(new Facility(HOTEL, lat, lon));
                if (random.nextBoolean()) facilityList.add(new Facility(SHOPPING_MALL, lat, lon));
            }
            if (rating >= 8) {
                if (random.nextBoolean())
                    facilityList.add(new Facility(GOLF_COURSE, lat, lon, title + "'s golf club", random.nextFloat(0, 10)));
                if (random.nextBoolean()) facilityList.add(new Facility(AIRPORT, lat, lon));
            }
            float facilityPercentage = facilityList.size() * 100f / FacilityType.values().length;
            int population = 0;
            try {
                population = random.nextInt((int) rating, (int) (facilityPercentage * rating * 1000));
            } catch (IllegalArgumentException e) {
                System.out.println((int) rating + " " + (int) (facilityPercentage * rating * 1000));
            }

            int roadsCount = (int) Math.ceil(rating / 1.5);
            if (roadsCount < 3) roadsCount = 3;

            if (titles.add(title)) {
                data.add(new Place(lat, lon, title, rating, facilityList, population, roadsCount));
            } else {
                i--;
            }
        }


        for (Place place : data) {
            int distance = 1;

            while (place.getPlaceConnections().size() < place.getRoadsCount()) {
                for (Place potentialConnection : data) {
                    if (place != potentialConnection && potentialConnection.distanceFrom(place) <= distance && !place.getPlaceConnections().contains(potentialConnection)) {
                        place.addToPlaceConnections(potentialConnection);
                        potentialConnection.addToPlaceConnections(place);
                        break;
                    }
                }
                distance++;
            }
        }

        return data;
    }

    /**
     * Returns the list of places generated by the GenerateData class.
     *
     * @return the list of places generated by the GenerateData class.
     */
    public List<Place> getData() {
        return placesData;
    }
}
